services:
  mirakurun:
    image: mirakurun
    container_name: Mirakurun
    build:
      context: ./mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    ports:
      - "40772:40772"
      - "9229:9229"
    volumes:
      - ./mirakurun/conf:/app-config
      - ./mirakurun/data:/app-data
    environment:
      TZ: "Asia/Tokyo"
    devices:
      - /dev/bus:/dev/bus
      - /dev/px4video0:/dev/px4video0
      - /dev/px4video1:/dev/px4video1
      - /dev/px4video2:/dev/px4video2
      - /dev/px4video3:/dev/px4video3
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m

  edcb_chscan:
    image: edcb
    container_name: EDCB_ChScan
    build:
      context: ./EDCB
    depends_on:
      - mirakurun
    network_mode: host
    volumes:
      - type: bind
        source: "./EDCB/edcb/Common.ini"
        target: "/var/local/edcb/Common.ini"
      - type: bind
        source: "./EDCB/edcb/EpgDataCap_Bon.ini"
        target: "/var/local/edcb/EpgDataCap_Bon.ini"
      - type: bind
        source: "./EDCB/edcb/EpgTimerSrv.ini"
        target: "/var/local/edcb/EpgTimerSrv.ini"
      - type: bind
        source: "./EDCB/edcb/Setting"
        target: "/var/local/edcb/Setting"

  edcb:
    image: edcb
    container_name: EDCB
    build:
      context: ./EDCB
    depends_on:
      mirakurun:
        condition: service_started
      edcb_chscan:
        condition: service_completed_successfully
    restart: always
    network_mode: host
    command: /usr/local/bin/EpgTimerSrv
    volumes:
      - type: bind
        source: "./EDCB/edcb/Common.ini"
        target: "/var/local/edcb/Common.ini"
      - type: bind
        source: "./EDCB/edcb/EpgDataCap_Bon.ini"
        target: "/var/local/edcb/EpgDataCap_Bon.ini"
      - type: bind
        source: "./EDCB/edcb/EpgTimerSrv.ini"
        target: "/var/local/edcb/EpgTimerSrv.ini"
      - type: bind
        source: "./EDCB/edcb/Setting"
        target: "/var/local/edcb/Setting"
      - type: bind
        source: "./EDCB/record"
        target: "/record"
