services:
  auto_gen_config:
    container_name: auto-gen-config.ISDBScanner
    build:
      context: ./autogen-config-with-isdb-scanner
    volumes:
      # ホストのpcscdを使う。これにより、ホストのpcscd.socketを止める必要がなくなる。
      # また、カードリーダーのUSBが物理的に抜けた場合でも、USBを再接続すればコンテナを再起動することなく再認識される。
      - /var/run/pcscd/pcscd.comm:/var/run/pcscd/pcscd.comm
      # MirakurunおよびEDCBの設定ファイル格納ディレクトリをマウント
      - ./mirakurun/conf:/mirakurun-config
      - ./EDCB/edcb/Setting:/edcb-setting
    devices:
      # /dev/bus は必須。これがなければチューナーが認識されない
      - /dev/bus:/dev/bus
      # 以下、チューナーのデバイスファイル
      - /dev/px4video0
      - /dev/px4video1
      - /dev/px4video2
      - /dev/px4video3
      - /dev/px4video4
      - /dev/px4video5
      - /dev/px4video6
      - /dev/px4video7
    logging:
      # ログはjournaldで記録する
      # デフォルトのjson-fileはログが /var/lib/docker/containers/*/*-json.log ファイルに記録される一方、
      # journaldの場合はログが /var/log/ 以下に集約されるため、
      # log2ramやzram-configのような書き込み頻度を抑えてSDカードの寿命を伸ばすソフトウェアが使用しやすい。
      driver: journald
      options:
        tag: dtv-autogen-config
    # いわゆるPID1問題を回避するため、Tiniを使用する
    # see https://zenn.dev/sato_frontend/articles/fc49ffb2fe5dfc
    init: true

  mirakurun:
    image: mirakurun
    build:
      context: ./mirakurun
    container_name: Mirakurun
    depends_on:
      auto_gen_config:
        condition: service_completed_successfully
    volumes:
      - ./mirakurun/conf:/app-config
      - ./mirakurun/data:/app-data
      # Note: Mirakurun公式のdocker-compose.ymlでは /var/run と /opt もホストと共有されている
      #       see https://github.com/Chinachu/Mirakurun/blob/61c4155d2535c56fbf6fd379c5e8aba779fd642b/docker/docker-compose.yml#L41-L42
      #       しかし、実際に運用する上でこれらのディレクトリに有用なファイルは記録されているようには見えない。
      #       いちおう公式に従っておくものの、マウントしなくても良いのかもしれない。
      - ./mirakurun/run:/var/run
      - ./mirakurun/opt:/opt
      # ホストのpcscdを使う。これにより、ホストのpcscd.socketを止める必要がなくなる。
      # また、カードリーダーのUSBが物理的に抜けた場合でも、USBを再接続すればコンテナを再起動することなく再認識される。
      - /var/run/pcscd/pcscd.comm:/var/run/pcscd/pcscd.comm
    environment:
      TZ: "Asia/Tokyo"
      DISABLE_PCSCD: 1
      DISABLE_B25_TEST: 1
      DOCKER_NETWORK: host
      # for debug
      LOG_LEVEL: "3"
      DEBUG: "true"
    network_mode: host
    restart: always
    logging:
      # ログはjournaldで記録する
      # デフォルトのjson-fileはログが /var/lib/docker/containers/*/*-json.log ファイルに記録される一方、
      # journaldの場合はログが /var/log/ 以下に集約されるため、
      # log2ramやzram-configのような書き込み頻度を抑えてSDカードの寿命を伸ばすソフトウェアが使用しやすい。
      driver: journald
      options:
        tag: dtv-mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    device_cgroup_rules:
      - 'c *:* rmw'
    devices:
      # /dev/bus は必須。これがなければチューナーが認識されない
      - /dev/bus:/dev/bus
      # 以下、チューナーのデバイスファイル
      - /dev/px4video0:/dev/px4video0
      - /dev/px4video1:/dev/px4video1
      - /dev/px4video2:/dev/px4video2
      - /dev/px4video3:/dev/px4video3
      - /dev/px4video4:/dev/px4video4
      - /dev/px4video5:/dev/px4video5
      - /dev/px4video6:/dev/px4video6
      - /dev/px4video7:/dev/px4video7
    tmpfs:
      - /tmp

  edcb_chscan:
    image: edcb
    container_name: EDCB_ChScan
    build:
      context: ./EDCB
    depends_on:
      - mirakurun
    network_mode: host
    volumes:
      - type: bind
        source: "./EDCB/edcb/Common.ini"
        target: "/var/local/edcb/Common.ini"
      - type: bind
        source: "./EDCB/edcb/EpgDataCap_Bon.ini"
        target: "/var/local/edcb/EpgDataCap_Bon.ini"
      - type: bind
        source: "./EDCB/edcb/EpgTimerSrv.ini"
        target: "/var/local/edcb/EpgTimerSrv.ini"
      - type: bind
        source: "./EDCB/edcb/Setting"
        target: "/var/local/edcb/Setting"

  edcb:
    image: edcb
    container_name: EDCB
    build:
      context: ./EDCB
    depends_on:
      mirakurun:
        condition: service_started
      edcb_chscan:
        condition: service_completed_successfully
    restart: always
    network_mode: host
    command: /usr/local/bin/EpgTimerSrv
    volumes:
      - type: bind
        source: "./EDCB/edcb/Common.ini"
        target: "/var/local/edcb/Common.ini"
      - type: bind
        source: "./EDCB/edcb/EpgDataCap_Bon.ini"
        target: "/var/local/edcb/EpgDataCap_Bon.ini"
      - type: bind
        source: "./EDCB/edcb/EpgTimerSrv.ini"
        target: "/var/local/edcb/EpgTimerSrv.ini"
      - type: bind
        source: "./EDCB/edcb/Setting"
        target: "/var/local/edcb/Setting"
      - type: bind
        source: "./EDCB/record"
        target: "/record"
